language: node_js
node_js:
  - '4.0'
script: ./test
deploy:
    provider: npm
    api_key: $NPM_AUTH_TOKEN
    on:
        branch: npm
notifications:
  email:
    recipients:
      - ericuldall@gmail.com
